env:
  node: true
  es6: true
  mocha: true
extends: airbnb-base
plugins:
  - import
  - mocha
rules:
  no-param-reassign: 0
  no-console: 0
  mocha/no-exclusive-tests: error
settings:
  import/resolver:
    - node
