language: node_js
node_js:
  - '7'
before_script:
  - npm install
  - npm run babel
script:
  - npm run lint
  - npm test
deploy:
  provider: npm
  email: hydrangea56@me.com
  api_key:
    secure: P1KTOdr7c1t6lqrPTaUATy71SqC/UQcsgX5uGn5/7L6H73tFt3L1rUq0yct54AbRj/ObZ2MdgUahu+gEmB5pwUDtVHPsPuzEybaqxM4be1/ZAU8ZJkwxwEpgDwaO/O7VdS9GIE95HTLUw+ICF2rnmRy3KxUNq0Ts1HiPpIT4zznYxdDMfA4rLMM7ZEV2COkljnl+/W61F3pMA2mMPqrfteIE8/7KRvq+hjoeezw+rvDnwGKAGwKzOJqdNLQD4zKB+unTdWDX8k2fenRWKBSEbBud1EU2xTuWLcqeqQdgv5QYDCilK1BVUI0ShByJ0UWvmqHvFRyahMxiVF+6cx4KF3XxIlPVQnwyM0sOwx6+WyqboOcfx1d3myoTGi3URVbzss5D3olZjdmv3TT34HVj2HdNERO9mZ8qU9TOCAipUFouFFUV8xqfKKHABs5ifbo5LQ2b9OcK02O2e4wQTWqLRA4LLbVyuXHneJT7/JXO8KgO6n1KAu6s9Ori+VefKCQTbxMeX/SYq6VCj0Xy8ZmUvDaVKo7M0dHTwg9bI8i1w0oHGjNSFVzS+eYwcig/bY2Zyb9r0jnr46XpW+jHsRi+P+w4sVoqESxWPbSNddkxOgPr2Fr3VDpWwItAQ7F0IhBu7iZer7hPtJrzvf5imc/hm4wp90yQPApMs9P8u24ANFs=
  skip_cleanup: true
  on:
    branch: master
