language: node_js
node_js:
  - "7"
before_script:
  - npm install
  - npm run babel
script:
  - npm run lint
  - npm test
deploy:
  provider: npm
  email: hydrangea56@me.com
  api_key:
    secure: OfT4xVjsWQfCf+oFQdssqBAoCIeyWgWz81epWINU/GRygRlfFs4YmY8eYnEcrsbfvuVPYn/sQFrz4EJyCUfbR3MOl2Dk6MSnR5awt+SiyvYANCJwMVYJROzfxTe/VL8SrY/vuYUXbc7kICqFka2Ip0PQTAIEVcZsEbdHTMqWtNWebZSiC/zj1KXMn4kL0Af+siTTBtzSbhGkvFy5qJ2GxChEUs/AdE/E43C70o5CtwcWKk0zcGN3tp1uddCd+u5BJHbqxNMEQygNTAe/vPZh2/1VV5I+Pe3D/oWQYA7Os0WC/a1wi16JCn3EGFI0kmWVsv5gRC13CzI15XNI7y0JP1oLVrtVtyefacOqj6ztdtzsJJuITOhIphEtTG5rag/PMSbie+hGApo5Fps+HkOYoB0lSlLXW9H6ndZTPdTsLM7oiQ1MT3maVyE0na/t7np2SCAodp693zmL5GUdcerpT6dKluQa6P/IaWWauzBKypxRLSpqMtsa2K8un9kLrQngx6KlRDoPA2kEcKTYzgy5GqS68twHznR9ta+YL0JUqwH/Lt7dukIsFsQ04vfp6Vx9tjy2Jns7UCtgwhQfV5jF+o8LQpgVigRIrHI0O5ekesAN8ESnNh3b7c9gP76KdBqtMdbfzSB2NfmVgAbByUFYueF9wGY599zZClMBK9kmjAc=
  skip_cleanup: true
  on:
    branch: master
